// Avatar mapping: translation key -> English filename
export const avatarMapping: Record<string, string> = {
  'jacare': 'Alligator',
  'tamia': 'Chipmunk', 
  'esquilo_gopher': 'Gopher',
  'ligre': 'Liger',
  'quagga': 'Quagga',
  'tamandua': 'Anteater',
  'chupacabra': 'Chupacabra',
  'urso_pardo': 'Grizzly',
  'lhama': 'Llama',
  'coelho': 'Rabbit',
  'tatu': 'Armadillo',
  'corvo_marinho': 'Cormorant',
  'porco_espinho': 'Hedgehog',
  'peixe_boi': 'Manatee',
  'guaxinim': 'Raccoon',
  'auroque': 'Auroch',
  'coiote': 'Coyote',
  'hipopotamo': 'Hippo',
  'visao': 'Mink',
  'rinoceronte': 'Rhino',
  'axolotl': 'Axolotl',
  'corvo': 'Crow',
  'hiena': 'Hyena',
  'macaco': 'Monkey',
  'ovelha': 'Sheep',
  'texugo': 'Badger',
  'dingo': 'Dingo',
  'ibex': 'Ibex',
  'alce': 'Moose',
  'musaranho': 'Shrew',
  'morcego': 'Bat',
  'dinossauro': 'Dinosaur',
  'ifrit': 'Ifrit',
  'narval': 'Narwhal',
  'gamba': 'Skunk',
  'castor': 'Beaver',
  'golfinho': 'Dolphin',
  'iguana': 'Iguana',
  'orangotango': 'Orangutan',
  'esquilo': 'Squirrel',
  'bufalo': 'Buffalo',
  'pato': 'Duck',
  'chacal': 'Jackal',
  'lontra': 'Otter',
  'tigre': 'Tiger',
  'camelo': 'Camel',
  'elefante': 'Elephant',
  'canguru': 'Kangaroo',
  'panda': 'Panda',
  'tartaruga': 'Turtle',
  'capivara': 'Capybara',
  'furao': 'Ferret',
  'coala': 'Koala',
  'pinguim': 'Penguin',
  'morsa': 'Walrus',
  'camaleao': 'Chameleon',
  'raposa': 'Fox',
  'kraken': 'Kraken',
  'ornitorrinco': 'Platypus',
  'lobo': 'Wolf',
  'guepardo': 'Cheetah',
  'sapo': 'Frog',
  'lemure': 'Lemur',
  'abobora': 'Pumpkin',
  'carcaju': 'Wolverine',
  'chinchila': 'Chinchilla',
  'girafa': 'Giraffe',
  'leopardo': 'Leopard',
  'python': 'Python',
  'wombat': 'Wombat',
};

// Legacy support - keep the old randomNicks for backward compatibility
export const randomNicks: Record<string, string> = {
  'Jacaré Anônimo': 'Alligator',
  'Tamiá Anônimo': 'Chipmunk',
  'Esquilo Anônimato': 'Gopher',
  'Ligre Anônimo': 'Liger',
  'Quagga Anônimo': 'Quagga',
  'Tamanduá Anônimo': 'Anteater',
  'Chupacabra Anônimo': 'Chupacabra',
  'Urso-pardo Anônimo': 'Grizzly',
  'Lhama Anônima': 'Llama',
  'Coelho Anônimo': 'Rabbit',
  'Tatu Anônimo': 'Armadillo',
  'Corvo-marinho Anônimo': 'Cormorant',
  'Porco-espinho Anônimo': 'Hedgehog',
  'Peixe-boi Anônimo': 'Manatee',
  'Guaxinim Anônimo': 'Raccoon',
  'Auroque Anônimo': 'Auroch',
  'Coiote Anônimo': 'Coyote',
  'Hipopótamo Anônimo': 'Hippo',
  'Visão Anônima': 'Mink',
  'Rinoceronte Anônimo': 'Rhino',
  'Axolotl Anônimo': 'Axolotl',
  'Corvo Anônimo': 'Crow',
  'Hiena Anônima': 'Hyena',
  'Macaco Anônimo': 'Monkey',
  'Ovelha Anônima': 'Sheep',
  'Texugo Anônimo': 'Badger',
  'Dingo Anônimo': 'Dingo',
  'Íbex Anônimo': 'Ibex',
  'Alce Anônimo': 'Moose',
  'Musaranho Anônimo': 'Shrew',
  'Morcego Anônimo': 'Bat',
  'Dinossauro Anônimo': 'Dinosaur',
  'Ifrit Anônimo': 'Ifrit',
  'Narval Anônimo': 'Narwhal',
  'Gambá Anônimo': 'Skunk',
  'Castor Anônimo': 'Beaver',
  'Golfinho Anônimo': 'Dolphin',
  'Iguana Anônima': 'Iguana',
  'Orangotango Anônimo': 'Orangutan',
  'Esquilo Anônimo': 'Squirrel',
  'Búfalo Anônimo': 'Buffalo',
  'Pato Anônimo': 'Duck',
  'Chacal Anônimo': 'Jackal',
  'Lontra Anônima': 'Otter',
  'Tigre Anônimo': 'Tiger',
  'Camelo Anônimo': 'Camel',
  'Elefante Anônimo': 'Elephant',
  'Canguru Anônimo': 'Kangaroo',
  'Panda Anônimo': 'Panda',
  'Tartaruga Anônima': 'Turtle',
  'Capivara Anônima': 'Capybara',
  'Furão Anônimo': 'Ferret',
  'Coala Anônimo': 'Koala',
  'Pinguim Anônimo': 'Penguin',
  'Morsa Anônima': 'Walrus',
  'Camaleão Anônimo': 'Chameleon',
  'Raposa Anônima': 'Fox',
  'Kraken Anônimo': 'Kraken',
  'Ornitorrinco Anônimo': 'Platypus',
  'Lobo Anônimo': 'Wolf',
  'Guepardo Anônimo': 'Cheetah',
  'Sapo Anônimo': 'Frog',
  'Lêmure Anônimo': 'Lemur',
  'Abóbora Anônima': 'Pumpkin',
  'Carcaju Anônimo': 'Wolverine',
  'Chinchila Anônima': 'Chinchilla',
  'Girafa Anônima': 'Giraffe',
  'Leopardo Anônimo': 'Leopard',
  'Python Anônimo': 'Python',
  'Wombat Anônimo': 'Wombat',
};

export class RandomNicks {
  // New method that returns translation key instead of hardcoded Portuguese
  static getRandomKey() {
    const keys = Object.keys(avatarMapping);
    const randomIndex = Math.floor(Math.random() * keys.length);
    return keys[randomIndex];
  }

  // Get English filename from translation key
  static getEnglishFromKey(key: string) {
    return avatarMapping[key];
  }

  // Legacy method for backward compatibility
  static get() {
    const nicks = Object.keys(randomNicks);
    const randomIndex = Math.floor(Math.random() * nicks.length);
    return nicks[randomIndex];
  }

  // Legacy method for backward compatibility
  static getEnglish(nick: string) {
    return randomNicks[nick];
  }
}
